version: '3'

services:
  app:
    env_file:
      - .env
    container_name: uphold_challenge
    image: uphold:latest
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  postgres:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DATABASE}

    volumes:
      - ./db-data/:/var/lib/postgresql/data/
